name: SetHomePlugin
main: SetHomePlugin\Main
version: 1.0.0
api: 5.0.0
author: Enolam
description: Système de homes avec plusieurs maisons, cooldown et téléportation.

permissions:
  sethomeplugin.sethome:
    default: true

  sethomeplugin.home:
    default: true

  sethomeplugin.delhome:
    default: true

  sethomeplugin.homes:
    default: true